apiVersion: v1
kind: Pod
metadata:
  name: volume-sharing
spec:
  containers:
  - name: apache
    image: httpd
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir: {}