apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  type: NodePort
  selector:
    app: apache
    env: dev
    tag: nodeport-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 30007