apiVersion: v1
kind: Pod
metadata:
  name: volume-sharing-1
spec:
  containers:
  - name: apache
    image: httpd
    volumeMounts:
    - mountPath: /data
      name: data-volume
  volumes:
  - name: data-volume
    hostPath:
      path: /vagrant/Hands-on/5-k8-pods-resource/3-volumes/Host-path/data-volume #directory on host
      type: Directory #optional 