apiVersion: v1
kind: Service
metadata:
  name: cluster-service
spec:
  type: ClusterIP
  selector:
    app: apache
    env: dev
    tag: cluster-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80